apiVersion: v1
kind: Service
metadata:
  name: fonicy-service
spec:
  selector:
    app: fonicy
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 8000
