apiVersion: v1
kind: Service
metadata:
  name: fonicy-service
spec:
  selector:
    app: fonicy
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080:80
      nodePort: 8080:80